<?php

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ModuleSeeder extends Seeder
{
    public function run(): void
    {
        $modules = [
            [
                'name'  => 'CRIME SCENE INVESTIGATION:',
                'intro' => 'A Crime Scene Investigation (CSI) game is a mystery and problem-solving game where players act as investigators who analyze evidence to solve a crime. The main goal of the game is to collect clues, examine the crime scene, question suspects, and use logical thinking to identify the criminal.',
                'how_to_play' => [
                    'A Crime Scene Investigation game is played by first setting up a crime scene with different clues and pieces of evidence.',
                    'Players are then divided into teams of investigators who carefully examine the scene and collect clues.',
                    'After gathering the evidence, the teams analyze it to understand what happened and compare it with suspect statements.',
                    'Using the information they find, players discuss their ideas and build a theory about the crime.',
                    'At the end of the game, each team presents their conclusion and identifies the criminal based on the evidence.',
                ],
                'rules' => '1. Respect the Crime Scene Players must carefully examine the crime scene without disturbing or removing evidence unless instructed. Observation is the first step in solving the case. 2. Collect Evidence Systematically Clues such as fingerprints, objects, notes, or photographs should be collected and recorded properly. Each piece of evidence must be documented before analysis. 3. Work as a Team Players may work in teams and share information with each other. Cooperation helps in connecting clues and building a complete understanding of the crime. 4. Analyze the Evidence After collecting clues, players must examine them carefully to determine their relevance. This may include matching fingerprints, identifying weapons, or interpreting written clues. 5. Question the Suspects Players may interview suspects or read suspect statements. They should compare statements with the evidence to identify inconsistencies. 6. Follow Logical Reasoning Players must rely on logic and evidence rather than guessing. Every accusation should be supported by clues found during the investigation. 7. Present the Final Conclusion At the end of the game, players must present who they think committed the crime, explain the motive, and describe the evidence that proves their conclusion. 8. No Changing Evidence Players are not allowed to create or alter evidence. Only the clues provided in the game can be used to solve the mystery.',
                'registration' => [
                    '4000 rs',
                ],
                'early_bird_price' => '4000 rs',
                'normal_price' => '4000 rs',
                'first_prize'  => '12000 rs',
                'second_prize' => '8000 rs',
                'min_delegations' => 8,
                'max_delegations' => 64,
                'min_participants' => 5,
                'max_participants' => 5,
                'team_size' => 5,
                'image_path' => 'assets/modules/crime-scene-investigation.jpg',
            ],
            [
                'name'  => 'TRAITOR',
                'intro' => 'Traitor is a social deduction game where players work together to complete missions or survive while secretly trying to uncover who among them is betraying the group. In this game, most players have one role as loyal members, while one or more are designated as traitors whose goal is to sabotage the group without being caught.',
                'how_to_play' => [
                    'Traitors– "Welcome to Hogwarts: The Betrayal Within" Missions',
                    'ROUND 1: Spell Training (Warm-Up Missions)',
                    'Goal: Build trust + introduce gameplay',
                    '1. Wingardium Leviosa',
                    'Teams must carry a lightweight object (ball/book) using only sticks/wands.',
                    'If it drops => restart.',
                    'Traitors can "accidentally" mess up balance.',
                    '2. Potion Panic',
                    'Players memorize a sequence of colored liquids/items.',
                    'Recreate it correctly within time.',
                    'Traitors subtly misguide the order.',
                    '3. Spell Relay',
                    'Relay race but each player must perform a "spell action" (spin, jump, clap combo).',
                    'Traitors delay or confuse teammates.',
                    'ROUND 2: The Forbidden Forest',
                    'Goal: Movement + clue hunting + confusion',
                    '4. Horcrux Hunt',
                    'Hidden objects around the garden.',
                    'Some are real, some fake.',
                    'Traitors can hide real ones or bring fake ones.',
                    '5. The Cursed Scrolls',
                    'Players find scrolls with clues.',
                    'Some scrolls contain lies planted by traitors.',
                    'Forces players to question everything.',
                    '6. Follow the Patronus',
                    'One player secretly knows the correct path/sequence.',
                    'Others must trust them.',
                    'If that player is a traitor = chaos.',
                    'ROUND 3: Dark Magic Rises',
                    'Goal: Pressure + sabotage',
                    '7. The Silent Curse',
                    'One player gets secretly "cursed" (eliminated).',
                    'Others must figure out how/why.',
                    'No obvious clues -> paranoia rises.',
                    '8. The Broken Spell',
                    'Team must solve a puzzle (words/symbols).',
                    'Missing pieces hidden in garden.',
                    'Traitors can delay or pretend to help.',
                    '9. Magic Barrier',
                    'Team must pass through obstacles (ropes, cones, zones) without touching.',
                    'Traitors intentionally trigger penalties.',
                    'ROUND 4: The Great Hall Trial',
                    'Goal: Drama + eliminations',
                    '10. Accusation Circle',
                    'Players sit in circle.',
                    'Each gets 30-60 sec to defend or accuse.',
                    'Voting -> one expelled.',
                    '11. Veritaserum Challenge',
                    'Selected players must answer rapid-fire questions.',
                    'Others judge truth vs lie.',
                    'Traitors must lie smartly.',
                    'FINAL ROUND: The Last Spell',
                    'Goal: High stakes ending',
                    '12. The Final Ritual',
                    'Team must complete a multi-step mission:',
                    'Collect items.',
                    'Solve final clue.',
                    'Perform "ritual" together.',
                    'Traitors try to ruin timing or give wrong info.',
                    'Secret Power Cards (Add These!)',
                    'Give 2-3 random players:',
                    'Invisibility Cloak -> immune from elimination once.',
                    'Marauder\'s Map -> reveal one player\'s identity.',
                    'Potion of Truth -> force someone to answer honestly.',
                    'Execution Tips (IMPORTANT)',
                    'Keep missions short (5-10 mins each).',
                    'Always mix physical + mental tasks.',
                    'After every 2-3 missions -> bring players back for discussion.',
                    'Build tension gradually (don\'t rush eliminations early).',
                    'PRO TIP (What makes it elite)',
                    'Don\'t just run missions - build a story.',
                    'Example:',
                    'Start: "Welcome to Hogwarts".',
                    'Middle: "Dark magic is spreading...".',
                    'End: "The fate of Hogwarts lies in your hands...".',
                ],
                'rules' => 'Social deduction format: loyal members must complete missions while identifying hidden traitors. Traitors aim to sabotage progress without being exposed.',
                'registration' => [
                    '2000 rs',
                ],
                'early_bird_price' => '2000 rs',
                'normal_price' => '2000 rs',
                'first_prize'  => '15000 rs',
                'second_prize' => '10000 rs',
                'min_delegations' => 16,
                'max_delegations' => 64,
                'min_participants' => 1,
                'max_participants' => 1,
                'team_size' => 1,
                'image_path' => 'assets/modules/traitors.jpg',
            ],
            [
                'name'  => 'Ludo',
                'intro' => 'It\'s a board game where you roll dice to move your tokens around, trying to get all of them home before the others.',
                'how_to_play' => [
                    'Ludo is a board game played by 2-4 players where each player chooses a color and gets four tokens.',
                    'Players take turns rolling a dice, and they must roll a 6 to move a token from the starting area onto the board.',
                    'Tokens move according to the number rolled on the dice, and landing on an opponent\'s token sends it back to the start.',
                    'Players continue moving their tokens around the board toward the home area.',
                    'The first player to move all four tokens to the center home wins the game.',
                ],
                'rules' => 'Played by 2-4 players, each with four tokens of a color. Roll a 6 to move a token out of the starting area. Move tokens according to the dice roll; rolling a 6 gives an extra turn. Capture opponent tokens by landing on them; sent back to start. Some safe squares protect tokens from capture. Move tokens around the board to reach your colored home column. First player to get all four tokens to the center home wins.',
                'registration' => [
                    '1000 rs',
                ],
                'early_bird_price' => '1000 rs',
                'normal_price' => '1000 rs',
                'first_prize'  => '5000',
                'second_prize' => '2500',
                'min_delegations' => 10,
                'max_delegations' => 64,
                'min_participants' => 1,
                'max_participants' => 1,
                'team_size' => 1,
                'image_path' => 'assets/modules/ludo.jpg',
            ],
            [
                'name'  => 'Min 2 win',
                'intro' => 'Min 2 Wit It! It\'s a high-energy game where you\'ve got 2 minutes to complete hilarious or tough challenges. Think fast, be quick-witted, and win big. Typically in Min 2 Wit It, you\'ll get challenges like rapid-fire trivia, word puzzles, or silly tasks.',
                'how_to_play' => [
                    'You\'re given 2 minutes, and you\'ve gotta complete as many challenges as possible.',
                    'Each challenge you nail gets you points or prizes.',
                    'The faster and more creative you are, the more you win!',
                    'Hosts will guide you, throw challenges.',
                ],
                'rules' => 'Complete challenges in 2 minutes, earn points/prizes. Host guides, you perform, creativity and speed = wins.',
                'registration' => [
                    '1000 rs',
                ],
                'early_bird_price' => '1000 rs',
                'normal_price' => '1000 rs',
                'first_prize'  => '5000 rs',
                'second_prize' => '2500 rs',
                'min_delegations' => 10,
                'max_delegations' => 64,
                'min_participants' => 1,
                'max_participants' => 1,
                'team_size' => 1,
                'image_path' => 'assets/modules/min-2-win-it.jpg',
            ],
            [
                'name'  => 'BOB (Battle Of The Bands )',
                'intro' => 'A Battle of the Bands is a music competition where different bands perform live to compete for the title of the best band. Each band showcases its musical talent, stage presence, and creativity in front of an audience and a panel of judges.',
                'how_to_play' => [
                    'The performances are usually evaluated based on musicianship, originality, coordination, and audience engagement.',
                    'At the end of the event, the band with the highest score or the best performance is declared the winner.',
                ],
                'rules' => 'Judges usually evaluate bands using several criteria to measure their musical ability and performance quality: Musicianship - Skill in playing instruments and singing accurately. Originality & Creativity - Unique style, songwriting, or arrangement of music. Coordination - How well band members perform together as a team. Stage Presence - Confidence, energy, and interaction with the audience. Sound Quality - Balance of instruments, clarity, and overall musical harmony. Audience Engagement - Ability to attract and excite the audience.',
                'registration' => [
                    '6000 rs',
                ],
                'early_bird_price' => '6000 rs',
                'normal_price' => '6000 rs',
                'first_prize'  => '50,000',
                'second_prize' => '30,000',
                'min_delegations' => 25,
                'max_delegations' => 64,
                'min_participants' => 6,
                'max_participants' => 6,
                'team_size' => 6,
                'image_path' => 'assets/modules/battle-of-the-bands.jpg',
            ],
            [
                'name'  => 'Futsal',
                'intro' => 'Dummy intro - to be updated.',
                'how_to_play' => [
                    'Dummy how to play - to be updated.',
                ],
                'rules' => 'Dummy rules - to be updated.',
                'registration' => [
                    '8000rs',
                ],
                'early_bird_price' => '8000rs',
                'normal_price' => '8000rs',
                'first_prize'  => 'TBD',
                'second_prize' => 'TBD',
                'min_delegations' => 25,
                'max_delegations' => 64,
                'min_participants' => 5,
                'max_participants' => 10,
                'team_size' => 5,
                'image_path' => 'assets/modules/futsal.jpg',
            ],
            [
                'name'  => 'Throwball',
                'intro' => 'Dummy intro - to be updated.',
                'how_to_play' => [
                    'Dummy how to play - to be updated.',
                ],
                'rules' => 'Dummy rules - to be updated.',
                'registration' => [
                    '8000rs',
                ],
                'early_bird_price' => '8000rs',
                'normal_price' => '8000rs',
                'first_prize'  => 'TBD',
                'second_prize' => 'TBD',
                'min_delegations' => 5,
                'max_delegations' => 32,
                'min_participants' => 7,
                'max_participants' => 12,
                'team_size' => 7,
                'image_path' => 'assets/modules/throw-ball.jpg',
            ],
            [
                'name'  => 'Paddle',
                'intro' => 'Dummy intro - to be updated.',
                'how_to_play' => [
                    'Dummy how to play - to be updated.',
                ],
                'rules' => 'Dummy rules - to be updated.',
                'registration' => [
                    '2500rs',
                ],
                'early_bird_price' => '2500rs',
                'normal_price' => '2500rs',
                'first_prize'  => 'TBD',
                'second_prize' => 'TBD',
                'min_delegations' => 10,
                'max_delegations' => 64,
                'min_participants' => 2,
                'max_participants' => 2,
                'team_size' => 2,
                'image_path' => 'assets/modules/paddle.jpg',
            ],
            [
                'name'  => 'Basketball',
                'intro' => 'Dummy intro - to be updated.',
                'how_to_play' => [
                    'Dummy how to play - to be updated.',
                ],
                'rules' => 'Dummy rules - to be updated.',
                'registration' => [
                    '8000rs',
                ],
                'early_bird_price' => '8000rs',
                'normal_price' => '8000rs',
                'first_prize'  => 'TBD',
                'second_prize' => 'TBD',
                'min_delegations' => 8,
                'max_delegations' => 32,
                'min_participants' => 5,
                'max_participants' => 10,
                'team_size' => 5,
                'image_path' => 'assets/modules/basket-ball.jpg',
            ],
            [
                'name'  => 'Dodgeball',
                'intro' => 'Dummy intro - to be updated.',
                'how_to_play' => [
                    'Dummy how to play - to be updated.',
                ],
                'rules' => 'Dummy rules - to be updated.',
                'registration' => [
                    '6000rs',
                ],
                'early_bird_price' => '6000rs',
                'normal_price' => '6000rs',
                'first_prize'  => 'TBD',
                'second_prize' => 'TBD',
                'min_delegations' => 7,
                'max_delegations' => 32,
                'min_participants' => 5,
                'max_participants' => 8,
                'team_size' => 5,
                'image_path' => 'assets/modules/dodge-ball.jpg',
            ],
            [
                'name'  => 'Table tennis',
                'intro' => 'Dummy intro - to be updated.',
                'how_to_play' => [
                    'Dummy how to play - to be updated.',
                ],
                'rules' => 'Dummy rules - to be updated.',
                'registration' => [
                    '1000rs',
                ],
                'early_bird_price' => '1000rs',
                'normal_price' => '1000rs',
                'first_prize'  => 'TBD',
                'second_prize' => 'TBD',
                'min_delegations' => 10,
                'max_delegations' => 64,
                'min_participants' => 1,
                'max_participants' => 1,
                'team_size' => 1,
                'image_path' => 'assets/modules/table-tennis.jpg',
            ],
            [
                'name'  => 'Chess',
                'intro' => 'Chess is a game of strategy, planning, and foresight, where players must anticipate their opponent\'s moves while carefully advancing their own pieces. It improves critical thinking, problem-solving, and decision-making skills and has been played worldwide for centuries as both a competitive sport and a recreational activity.',
                'how_to_play' => [
                    'Chess is a two-player strategy game where the goal is to checkmate the opponent\'s king.',
                    'The game is played on an 8x8 board, with each player controlling 16 pieces: one king, one queen, two rooks, two knights, two bishops, and eight pawns.',
                    'Each piece moves in a specific way, such as the king moving one square in any direction, the queen moving any number of squares in any direction, and the knight moving in an L-shape.',
                    'Players take turns moving one piece at a time, capturing opponent pieces by landing on their squares.',
                    'Special moves like castling, en passant, and pawn promotion add strategic depth.',
                    'The game ends when a king is checkmated, meaning it cannot escape capture, or in some cases, a draw occurs.',
                    'Chess is a game of strategy, planning, and critical thinking.',
                ],
                'rules' => 'Setup: 8x8 board; pieces in starting positions; queen on her color. Turns: Players alternate moves, one piece per turn. Piece Moves: Each piece moves differently (king 1 square, queen any direction, rook straight, bishop diagonal, knight L-shape, pawn forward/capture diagonal). Capture: Move onto opponent\'s square to take their piece. Check & Checkmate: King in check must move; game ends with checkmate. Special Moves: Castling, en passant, pawn promotion. Draws: Stalemate, insufficient material, threefold repetition, or fifty-move rule.',
                'registration' => [
                    '1000 rs',
                ],
                'early_bird_price' => '1000 rs',
                'normal_price' => '1000 rs',
                'first_prize'  => '5000 rs',
                'second_prize' => '2500 rs',
                'min_delegations' => 10,
                'max_delegations' => 64,
                'min_participants' => 1,
                'max_participants' => 1,
                'team_size' => 1,
                'image_path' => 'assets/modules/chess.jpg',
            ],
            [
                'name'  => 'FIFA',
                'intro' => 'The game combines skill, strategy, and quick reflexes, allowing players to compete against friends or AI opponents. Each team has unique players with different abilities, and matches follow standard football rules, including goals, fouls, and penalties.',
                'how_to_play' => [
                    'Choose a Team - Select your favorite club, national team, or create a custom team.',
                    'Understand the Controls - Use the controller buttons to pass, shoot, dribble, tackle, and switch players. Each button has a specific function, which may vary depending on the console.',
                    'Play Matches - Compete against AI or friends in full matches. The objective is to score more goals than the opponent before time runs out.',
                    'Defend and Attack - Control your players to defend against opponents and move strategically to create scoring opportunities.',
                    'Use Skills and Strategies - Master dribbling, skill moves, set pieces (corners, free kicks, penalties), and team formations for better performance.',
                    'Win the Game - Matches end when the full game time is completed, and the player or team with the most goals wins.',
                ],
                'rules' => 'Match Duration - Each game lasts a set time (usually 90 minutes in full simulation, or shorter for gameplay modes). Number of Players - Each team has 11 players, including a goalkeeper. Scoring Goals - The objective is to score more goals than the opponent within the match time. Starting Play - Matches start with a kickoff from the center of the field. Ball Out of Play - The ball is out if it crosses the goal line or touchline; restarts include throw-ins, goal kicks, and corner kicks. Fouls and Misconduct - Physical contact like pushing, tripping, or handball is penalized. Free kicks, penalties, or cards may be given. Offside Rule - An attacking player cannot be nearer to the opponent\'s goal than the second-last defender when receiving the ball. Winning the Game - The team with the most goals at the end wins; if tied, some modes allow extra time or penalty shootouts.',
                'registration' => [
                    '1500 rs',
                ],
                'early_bird_price' => '1500 rs',
                'normal_price' => '1500 rs',
                'first_prize'  => '10000 rs',
                'second_prize' => '6000 rs',
                'min_delegations' => 20,
                'max_delegations' => 64,
                'min_participants' => 1,
                'max_participants' => 1,
                'team_size' => 1,
                'image_path' => 'assets/modules/fifa.jpg',
            ],
            [
                'name'  => 'Badminton',
                'intro' => 'Fast reflexes, precise shots, and explosive rallies — bring your A-game to the badminton court and smash your way to the top.',
                'how_to_play' => [
                    'Matches follow BWF singles rules.',
                    'Best of 3 games; each game is played to 21 points.',
                    'A player wins a game by scoring 21 points with a 2-point lead (cap at 30).',
                    'Service alternates based on who wins each rally.',
                    'Tournament format: group stage followed by knockout rounds.',
                ],
                'rules' => 'Participants must provide their own rackets. Shuttlecocks will be provided. Proper sportswear and non-marking shoes are mandatory. Coaching from the sidelines is not permitted.',
                'registration' => [
                    '1000rs',
                ],
                'early_bird_price' => '1000rs',
                'normal_price' => '1000rs',
                'first_prize'  => 'PKR 12,000 + Trophy',
                'second_prize' => 'PKR 6,000 + Medal',
                'min_delegations' => 10,
                'max_delegations' => 64,
                'min_participants' => 1,
                'max_participants' => 1,
                'team_size' => 1,
                'image_path' => 'assets/modules/badminton.jpg',
            ],
        ];

        Module::query()->whereIn('name', ['Tug of War', 'Carrom'])->delete();

        foreach ($modules as $order => $module) {
            if (! array_key_exists('image_path', $module)) {
                $module['image_path'] = 'assets/modules/' . Str::slug($module['name']) . '.jpg';
            }
            Module::updateOrCreate(
                ['name' => $module['name']],
                array_merge($module, ['sort_order' => $order])
            );
        }
    }
}
